model:
  name: Recce
  num_classes: 1
config:
  lambda_1: 0.1
  lambda_2: 0.1
  distribute:
    backend: nccl
  optimizer:
    name: adam
    lr: 0.0002
    weight_decay: 0.00001
  scheduler:
    name: StepLR
    step_size: 22500
    gamma: 0.5
  resume: False
  resume_best: False
  id: FF++c40
  loss: binary_ce
  metric: Acc
  debug: False
#  device: "cuda:1"
#  ckpt: best_model_1000
data:
  train_batch_size: 32
  val_batch_size: 64
  test_batch_size: 64
  name: FaceForensics
  file: "./config/dataset/faceforensics.yml"
  train_branch: "train_cfg"
  val_branch: "test_cfg"
  test_branch: "test_cfg"
